### ISSUE TITLE
Unexpected autofocus

### ISSUE THREAD

**Issue by troolee** [ng2-ui/auto-complete#276]
Hi there, 

Found an unexpected behaviour. I've been using auto-complete 0.14.4 with reactive forms. In case if a field has initial value auto-complete input gets focus at startup.

Here is a plunker script that reproduces this: http://plnkr.co/edit/sFJOqsQXBEMUkGrKbhRH?p=preview

**Comment by allenhwkim** [comment]
This code has been recently added because users asked to set focus to the element when a new value is selected.

https://github.com/ng2-ui/auto-complete/blob/b37b8f4b3d99e6cbb3105af7ef105e1f29f6e8d3/src/auto-complete.directive.ts#L308-L315

However, as you mentioned to set focus does not seem right for initial status without user interaction. Let me see what I can do.

**Comment by rsaenen** [comment]
Hi,
Same issue here, the input with auto-complete directive takes autofocus.

**Comment by rsaenen** [comment]
Solved with 0.13.3 release.

**Comment by troolee** [comment]
Oh... This doesn't solve the issue... There was no issue on 0.13.3 I assume

**Comment by rsaenen** [comment]
Agreed, solved wasn't the right term... Don't hesitate to contribute to this package if you could. Thanks

**Comment by pablogarciamiranda** [comment]
Same issue here

**Comment by igorrius** [comment]
Hi there. Maybe my changes will help to resolve this problem. I had create PR https://github.com/ng2-ui/auto-complete/pull/288 where I had use a new property to make this behavior more configurable.

**Comment by rsaenen** [comment]
Hi, I'm still having this issue... No news?

**Comment by matteobaldelli** [comment]
Why was it implemented only in directive and not in component??
